create table contacts (id bigint generated by default as identity, email varchar(255), name varchar(255), user_id bigint, uuid  varchar(255), primary key (id));
create table player (id bigint generated by default as identity, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id));
create table users (id bigint generated by default as identity, passwd varchar(255), username varchar(255), permissions varchar(255), uuid  varchar(255), primary key (id));
create table AUTH_ACCESS_ELEMENT (auth_id bigint generated by default as identity, auth_token varchar(255), auth_permission varchar(255), primary key (auth_id));
alter table contacts add constraint FK_contacts_users foreign key (user_id) references users;
